# Site settings
author: Beth Holley
title: Flatiron Portfolio
header-img: img/home-bg.png
email: chocolatechipfaced@gmail.com
copyright_name: Beth Holley
description: > # this means to ignore newlines until "baseurl:"
  My Portfolio Blog for Coding
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  skullkid942

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
